{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-web-app
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          {{- range .Values.ingress.hosts }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: express-web-app
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
{{- end }}
