apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: express-web-app-metrics
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: express-web-app
  namespaceSelector:
    matchNames:
      - apps
  endpoints:
    - port: http
      interval: 10s
      path: /metrics
