namespace: apps

replicaCount: 2

image:
  repository: "730335276920.dkr.ecr.us-east-1.amazonaws.com/t2s-express-app"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 3000
  type: ClusterIP

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - path: /
      pathType: Prefix

resources: {}

# ---------------------------------------------------------
# AIOps Configuration
# ---------------------------------------------------------
aiops:
  enabled: true
  namespace: aiops

  image:
    repository: "730335276920.dkr.ecr.us-east-1.amazonaws.com/aiops-service"
    tag: "latest"
    pullPolicy: IfNotPresent

  service:
    port: 8080

  replicas:
    api: 1
    anomaly: 1
    finops: 1

  ingress:
    enabled: true
    className: nginx
    annotations: {}
    hosts:
      - path: /aiops
        pathType: Prefix
