image:
  repository: "REPLACE_WITH_REGISTRY/express-t2s"
  tag: "latest"

replicaCount: 3

ingress:
  enabled: true
  hosts:
    - host: "staging.express.local"
      paths:
        - path: /
          pathType: Prefix
