apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: express-app-alerts
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: express-alerts
      rules:

        - alert: ExpressHighErrorRate
          expr: express:error_rate > 2
          for: 2m
          labels:
            severity: critical
          annotations:
            description: "High error rate detected in Express Web App"
            summary: "Express app error rate above 2 req/s"

        - alert: ExpressHighLatencyP99
          expr: express:latency_p99 > 2
          for: 2m
          labels:
            severity: warning
          annotations:
            description: "Latency P99 is above normal threshold"
            summary: "High latency P99"

        - alert: ExpressLowRPS
          expr: express:rps < 1
          for: 5m
          labels:
            severity: info
          annotations:
            description: "Low RPS detected"
            summary: "Traffic to Express app is low"
