namespace: monitoring

image:
  repository: grafana/grafana
  tag: "11.2.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - path: /grafana
      pathType: Prefix

admin:
  user: admin
  password: "T2S#Grafana123"

datasource:
  prometheusUrl: "http://prometheus.monitoring.svc.cluster.local:9090"

dashboards:
  default:
    express-web-app:
      json: |
        {{ .Files.Get "dashboards/express-web-app.json" | nindent 8 }}

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "aiops-dashboards"
        orgId: 1
        folder: "AIOps-FinOps-DevSecOps"
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/aiops

dashboards:
  aiops:
    aiops-enterprise-dashboard:
      file: dashboards/aiops-enterprise-dashboard.json
