apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: express-t2s-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_WITH_YOUR_ORG/t2s-golden-project-template.git
    targetRevision: main
    path: helm/express-t2s
    helm:
      valueFiles:
        - ../../gitops/environments/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
