route:
  receiver: "webhook-receiver"
  group_by: ["alertname"]
  group_wait: 5s
  group_interval: 10s
  repeat_interval: 1m

receivers:
  - name: "webhook-receiver"
    webhook_configs:
      - url: "http://webhook-receiver:5001/alertmanager"
        send_resolved: true
