apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: aiops-alerts
  namespace: {{ .Values.namespace }}
spec:
  groups:
    - name: aiops.rules
      rules:
        - alert: HighCPU
          expr: container_cpu_usage_seconds_total > 0.8
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"
            description: "Container CPU > 80% for 1 minute"