{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aiops-api
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: "{{ $v }}"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          {{- range $.Values.ingress.hosts }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: aiops-api
                port:
                  number: 80
          {{- end }}
{{- end }}