apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "express-t2s.fullname" . }}
  labels:
    app: {{ include "express-t2s.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "express-t2s.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "express-t2s.name" . }}
    spec:
      containers:
        - name: {{ include "express-t2s.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
          {{- toYaml .Values.env | nindent 16 }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 15
            periodSeconds: 20
