apiVersion: v1
kind: Service
metadata:
  name: {{ include "express-t2s.fullname" . }}
  labels:
    app: {{ include "express-t2s.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "express-t2s.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
